### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by Micky373** [Micky373/JavaScript_Capstone#21]
Hello Reviewer,

This is the link to our project https://github.com/Micky373/JavaScript_Capstone/projects/1

We are two in the group:

- @Micky373 
- @eng-mohamed-eldeeb 

Thanks 😁

**Comment by elyor-doniyorov** [comment]
Hi @Micky373 and @eng-mohamed-eldeeb, 

In my opinion, your Kanban board is complete!  There is nothing else to say other than... it's time to start working on the tasks :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Micky373** [comment]
Closed
